### ISSUE TITLE
Mistake at js

### ISSUE THREAD

**Issue by xezon88** [doiftrue/Term_Meta_Image#1]
Maybe I'm stupid but I think that needs to be changed 

`$imgwrap.find( 'img' ).attr( 'src', selected.sizes.thumbnail.url );`  

for

`$imgwrap.find( 'img' ).attr( 'src', selected.url );`

At least for me in this configuration everything works ok

**Comment by xezon88** [comment]
this is my first ussues at github i'm happy

**Comment by xezon88** [comment]
hmm

**Comment by doiftrue** [comment]
Thanks for issue. 

It happens because in some cases there is not thumbnail size - normally it should be there. Add this fix in [this commit](https://github.com/doiftrue/Term_Meta_Image/commit/69c1f5fe4609c25db71414231f5a5afab0676f23).
